CREATE TABLE IF NOT EXISTS public.users
(
    user_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_first_name  VARCHAR(255) not null ,
    user_last_name  VARCHAR(255) not null ,
    user_money INT NOT NULL
    );